In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get total size
a.nbytes

12

In [9]:
# Get number of elements
a.size

3

### Accessing or changing specific rows or columns

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [r, c]
a[1, 5]

13

In [12]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [14]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specific element (work outside in)
b[0,1,1]

4

In [20]:
# replace a complete array 
b[:,1,:] = [[9,9],[8,8]]

In [21]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing different types of array 

In [22]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [24]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [25]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.97549507, 0.89987508],
       [0.3787375 , 0.2450666 ],
       [0.32072634, 0.51627533],
       [0.01040055, 0.35585643]])

In [27]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 3, -3,  6],
       [-4,  5,  6],
       [-2,  7, -2]])

In [28]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [30]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copying Arrays 

In [31]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics functions

In [32]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [33]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [36]:
print(a)
b = np.array([1,0,1,0])
a + b

[1 2 3 4]


array([2, 2, 4, 4])

In [40]:
# Take the cos
np.cos(a)

array([[0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231]])

### Linear Algebra 


In [38]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [39]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [41]:
stats = np.array([[1,2,3],[4,5,6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.min(stats)


1

In [43]:
np.max(stats, axis=1)


array([3, 6])

In [44]:
np.sum(stats, axis=0)


array([5, 7, 9])

### Reorganising array

In [45]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [47]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((5,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (5,3)

### Vectorisation for logistic regression

In [3]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("vectorized time: " + str(1000*(toc-tic))+ "ms")
c= 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("for loop: " + str(1000*(toc-tic))+ "ms")
    

250049.02474038454
vectorized time: 2.000093460083008ms
250049.0247403863
for loop: 735.0420951843262ms


### This concludes that vectorised version of the code takes about 350 times less than the for loop version